---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/3 20:14
---

local t,sz=taskqueue.poptask()

local a=seri.unpack(t)
print(a)

local name=a:getName()
local age=a:getAge()

print("the object name is"..name.." age is "..age)