---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/4 9:41
---

local MAIN_STATE=0

local TYPE_REQUIRE=0
local TYPE_INVOKE=1
local TYPE_CALLBACK=2

local M={}

local invoke_tool

M.analyzer=function(buffer,sz,target_id,type)
    print(target_id,type)
    if target_id==ID then
        if type==TYPE_INVOKE then
            invoke_tool(seri.unpack_remove(buffer))
        --todo:得益于luajava的引入，回调变得方便了起来
        --todo:    但并不意味着这里可以省略
        elseif true==TYPE_CALLBACK then

        end

    end
end

invoke_tool=function(module,name,...)
    require(module)[name](...)
end

M.cross_vm_require= function(target_id,module)
    local proxy={}
    setmetatable(proxy,{
        __index = function(t,key)
            return function(...)
                local b,_sz=seri.pack(module,key,...)
                thread.post(b,_sz,target_id,TYPE_INVOKE)
            end
        end
        })
    return proxy
end

return M
