---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/4 10:00
---
local cvm=require("cross_vm")
local m={}


m.new=function()
    return _thread.new()
end

m.close=function(id)
    _thread.free(id)
end

--runnable应该是一个函数
m.run=function(runnable)
    local id=m.new()
    local b,_sz=_seri.pack(runnable)
    _thread.post(b,_sz,id,cvm.TYPE_RUN)
end

return m