---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/17 13:01
---

local vm=require("cross_vm")
local thread=require("threadAPI")
local stt=thread.newState()

local recv=vm.cross_vm_require(stt,"test.java_object_recv")

recv.test("mike",18,function(arg,callback_)
    print("hahaha:"..arg)
    callback_("callback in ABB")
end,{b=6,a=function(arg)
    print(arg)
end})