---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/4 10:00
---
local cvm=require("cross_vm")
local m={}

m.service={}

m.subthread={}

--可以收获一个具名线程，
m.newState =function()
    local id=_thread.new()
    m.service[id]=1
    return id
end

--不能自己回收自己
m.closeState =function(id)
    if id==ID then
        error("recycle self not allowed")
    end
    m.service[id]=nil
    _thread.free(id)
end

--第一个为runnable，后面为接收的参数
--新建一个匿名线程，执行完就回收
m.run=function(runnable,...)
    local id=m.newState()
    local b,_sz=_seri.pack(runnable,{...})
    _thread.post(b,_sz,id,cvm.TYPE_RUN)
end

m.join=function(id)

end

return m