---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/4 10:00
---
local cvm=require("cross_vm")
local m={}

--可以收获一个具名线程，
m.new=function()
    return _thread.new()
end

m.close=function(id)
    _thread.free(id)
end

--runnable应该是一个无参函数
--新建一个匿名线程，执行完就回收
--todo 可以有第二个参数，实现线程池
m.run=function(runnable)
    local id=m.new()
    local b,_sz=_seri.pack(runnable)
    _thread.post(b,_sz,id,cvm.TYPE_RUN)
end

--todo 阻塞时可以构建一个谦让式的调度


return m