---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/28 20:28
---

local vm=require("cross_vm")
local thread=require("threadAPI")


local m={}

local export

export=function(n,callback)
    if n>0 then
        local id1=thread.newState()
        local id2=thread.newState()
        local pkg1=vm.cross_vm_require(id1,"test.create_and_close")
        local pkg2=vm.cross_vm_require(id2,"test.create_and_close")
        thread.introduce(id1,id2)
        thread.introduce(id2,id1)
        pkg1.export(n-1,function()
            if ID ~=0 then
                thread.closeState(ID,tqueue)
            end
        end)
        pkg2.export(n-1,function()  end)
        callback()
    end
end

m.export=export

if ID==0 then
    export(3,function()  end)
end

return m

