---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/28 19:55
---

local m={}

local function fib(n)
    return n < 2 and n or fib(n-1) + fib(n-2)
end

m.fib=function(n,callback)
    fib(n)
    callback()
end

m.close=function()
    local th=require("threadAPI")
    th.closeState(ID,tqueue)
end

return m;