---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/3 20:14
---

--local Fun=java.import("com.lockheed.parallelLJ.JustForFun")
--local a=java.new(Fun)
--a:setName("mike")
--a:setAge(18)
--
local vm=require("cross_vm")

local recv=vm.cross_vm_require(1,"java_object_recv")

recv.test("mike",18)

print("task done")

