---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/3 20:14
---

local vm=require("cross_vm")
local thread=require("threadAPI")

local Util=java.import("com.lockheed.parallelLJ.Util")
local TAG="JAVA_CALLBACK"

local callback_function={
    callbackFunction=function(self,ret)
        print(TAG, "callback in the lua")

        print(ret)
        print(ret.messageClass)
    end
}

-- 三行可以合成一个函数
local callback=java.proxy('com.lockheed.parallelLJ.callback',callback_function)
local handler=java.import('com.lockheed.parallelsdk.LuaCallbackDispatcher')
local proxy=handler:bind(callback)

local params={
    _picPath=picPath,
    cb_info={_cb=callback,
             _proxy=proxy
    },
    info={
        code=4060,
        msg={
            meta="CORE",
            detail="just do it"
        }
    }
}

Util:testComplex(params,false,proxy)







