---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/3 20:14
---

--local Fun=java.import("com.lockheed.parallelLJ.JustForFun")
--local a=java.new(Fun)
--a:setName("mike")
--a:setAge(18)
--
local vm=require("cross_vm")
local thread=require("threadAPI")
local vmvm=thread.newState()


local t={
    h=4,
    func=function()
        print("shared")
    end,
    ta={
        a=18,
        b="recursive"
    }
}

--print(str)
--print("dump completed"+str)
_SHARED.a=t
print(_SHARED.a)
print("pass")


local recv=vm.cross_vm_require(vmvm,"test.java_object_recv")

local r=2
--local r=2
thread.run(function()
    print("in runnable I can fly"..ID)
end)


recv.test("mike",18,function(arg,callback_)
    print("hahaha:"..arg)
    callback_("callback in ABB")
end,{b=6,a=function(arg)
    print(arg)
end})

print("task done")

