---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/28 22:25
---

local NUM_ACTORS = 10  -- 可调整Actor数量
local ii=0
-- Actor计算任务函数（斐波那契数列模拟CPU密集型操作）
local function cpu_task()
    local function fib(n)
        return n < 2 and n or fib(n-1) + fib(n-2)
    end

    fib(10)  -- 调整数值控制计算强度
    ii=ii+1
    coroutine.yield()
end

-- 创建Actor池
local actors = {}
for i = 1, NUM_ACTORS do
    actors[i] = coroutine.create(cpu_task)
end

-- 启动压力测试
local start = os.clock()
while ii<NUM_ACTORS do
    -- 轮询调度所有Actor
    for _, actor in ipairs(actors) do
        coroutine.resume(actor)
    end
end
local end_=os.clock()
print(end_-start)