---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/28 19:56
---

local vm=require("cross_vm")
local thread=require("threadAPI")


local ii=0
local max=10
local start=os.clock()
for i=1,max do
    local f=vm.cross_vm_require(thread.newState(),"test.fib")
    f.fib(10,function()
        ii=ii+1
        if ii==max then
            local end_=os.clock()
            print(end_-start)
        end
    end)
end
