---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/4/7 23:24
---


local vm=require("cross_vm")
local thread=require("threadAPI")


local ii=0
local max=1000
local start=os.clock()
for i=1,max do
    local f=vm.cross_vm_require(thread.newState(),"test.shared_get")
    if i%2==0 then
        f.export()
    else
        f.export2()
    end
end