---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/17 13:08
---

local t={
    h=4,
    func=function()
        print("shared")
    end,
    ta={
        a=18,
        b="recursive"
    }
}

_shared.wtlock()
_SHARED.a=t
_shared.unlock()