---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/17 13:08
---
---
local m={}

m.export=function()
    for i=1,10 do
        local h=0
        --_shared.rdlock()
        print("In "..ID.." the value is",_SHARED.a)
        --_shared.unlock()
        for j=1,100000 do
            h=h+1
        end
    end
end

m.export2=function()
    --_shared.wtlock()
    print("In "..ID.." change value")
    _SHARED.a=math.random()
    --_shared.unlock()
end

return m