---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/17 13:00
---

local vm=require("cross_vm")
local thread=require("threadAPI")


local rc={}
for i=1,10 do
    rc[i]=thread.run(function(number)
        print("I am thread "..ID..", "..number.." thread created")
        return ID,"return"..tostring(number)
    end,i)
end

local m={}
for i=1,10 do
    m[i]={thread.join(rc[i])}
end

print("return collected: ", m)
print("join done")