---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guan.
--- DateTime: 2025/3/17 13:01
---

local vm=require("cross_vm")
local thread=require("threadAPI")

-- 创建一个拥有独立线程的独立虚拟机
local stt=thread.newState()
local recv=vm.cross_vm_require(stt,"test.worker_thread_exec")

-- worker间唯一的调用形式，即rpc传参
recv.test("mike",18,function(arg,callback_)
    print("hahaha:"..arg)
    callback_("callback in ABB")
end,{b=6,a=function(arg)
    print(arg)
end})

-- 需要关闭虚拟机时手动回收，一般不需要
-- thread.close(stt)